export type DocSummary = {
  /** Stable identifier used as a React key and for selection state. */
  docId: string;
  label: string;
  /** Public URL, served from public/. Not necessarily derivable from docId —
   *  three of these files predate this sample and live where other samples
   *  already reference them. Do not "tidy" the paths. */
  path: string;
  /** Sent as the upload filename, so the backend's echo and generated code
   *  snippet name something recognisable. */
  filename: string;
  hasTextLayer: boolean;
  /** Drives both the strip filter and which schema preset loads. A string, not
   *  CategoryId, so an entry with an unrecognised category still renders. */
  category: string;
};

/**
 * The document list is code, not a directory scan.
 *
 * The backend used to own a registry and serve PDFs over `/api/doc/{id}`; it is
 * now stateless, and Next serves these statically from public/. A hardcoded
 * manifest is the whole mechanism — there is no endpoint to call and nothing to
 * fall back to.
 *
 * `Invoice AC-2025-1047.pdf`, `scanned-invoice.pdf` and
 * `happy-tooth-invoice-excel.pdf` were already in this repo, byte-identical to
 * the demo's copies, and are referenced from their existing paths rather than
 * duplicated.
 *
 * Two docIds from the original nine are deliberately absent: `construction`
 * and `accident-report` were byte-identical duplicates of
 * `westbridge-engineering-submittal-form` and
 * `emergency-dept-billing-worksheet` respectively (identical PNG renders; the
 * latter pair differs only in the PDF trailer /ID). Listing either would have
 * shown the same document twice under two names.
 * `westbridge-engineering-submittal-form` itself is gone now too (see the
 * construction category entry below), but `construction` stays off-limits as
 * a docId — reusing it for something unrelated would be confusing history,
 * and `emergency-dept-billing-worksheet` is still in the corpus, so
 * `accident-report` remains a live duplicate to avoid.
 */
/*
 * Invoice labels deliberately omit the word "invoice" — the category control
 * directly above the list already says "Invoices", so repeating it in all four
 * labels wasted the 208px rail column on a word the user just chose. Other
 * categories keep their document nouns because they are not redundant
 * ("Meridian income statement" under Finance, "Straight bill of lading" under
 * Logistics).
 *
 * Claims followed suit on 2026-08-06 (Jon's call): "Northgate auto claim (FNOL)"
 * became "Northgate auto (FNOL)". Only the redundant "claim" went — "auto" still
 * distinguishes it from a property claim, and FNOL is real claims jargon that a
 * prospect in that vertical reads as a signal rather than noise.
 *
 * Every label is now an IDENTITY, never a property. "Scanned" used to break that
 * rule: it named this document by the one attribute it shares with three others
 * (Lumen, Westbridge and the bill of lading are all scans too), so it read as a
 * category while its neighbours read as names. It is now "Vandelay Industries",
 * after the only proper noun the page carries. Scan-ness is signalled separately
 * in DocStrip, driven off `hasTextLayer`.
 */
export const DOCUMENTS: DocSummary[] = [
  {
    docId: "invoice-ac20251047",
    label: "Atlas Construction",
    path: "/invoices/Invoice AC-2025-1047.pdf",
    filename: "invoice-ac20251047.pdf",
    hasTextLayer: true,
    category: "invoices",
  },
  {
    docId: "lumen-invoice",
    label: "Lumen",
    path: "/documents/lumen-invoice.pdf",
    filename: "lumen-invoice.pdf",
    hasTextLayer: false,
    category: "invoices",
  },
  {
    docId: "scanned-invoice",
    label: "Vandelay Industries",
    path: "/documents/scanned-invoice.pdf",
    filename: "scanned-invoice.pdf",
    hasTextLayer: false,
    category: "invoices",
  },
  {
    docId: "happy-tooth-invoice-excel",
    label: "Happy Tooth (from Excel)",
    path: "/documents/happy-tooth-invoice-excel.pdf",
    filename: "happy-tooth-invoice-excel.pdf",
    hasTextLayer: true,
    category: "invoices",
  },
  {
    // Replaced westbridge-engineering-submittal-form on 2026-08-12 — that
    // document was a demo hazard (33-36s extractions, ~50% hosted-backend
    // failure rate; see SDK-051 in docs/internal/sdk-defects/). This is a
    // text-layer G702-style application and certificate for payment,
    // generated by scripts/generate-construction-payapp.py. Measured 9/9
    // success across openai/anthropic/bedrock (3 runs each), 3.96-7.86s,
    // before being wired in.
    docId: "construction-pay-application",
    label: "Cedar Hollow pay application",
    path: "/documents/construction-pay-application.pdf",
    filename: "construction-pay-application.pdf",
    hasTextLayer: true,
    category: "construction",
  },
  {
    docId: "bill-of-lading",
    label: "Straight bill of lading",
    path: "/documents/bill-of-lading.pdf",
    filename: "bill-of-lading.pdf",
    hasTextLayer: false,
    category: "logistics",
  },
  {
    docId: "emergency-dept-billing-worksheet",
    label: "ED billing worksheet",
    path: "/documents/emergency-dept-billing-worksheet.pdf",
    filename: "emergency-dept-billing-worksheet.pdf",
    hasTextLayer: true,
    category: "healthcare",
  },
  {
    docId: "meridian-income-statement",
    label: "Meridian income statement",
    path: "/documents/meridian-income-statement.pdf",
    filename: "meridian-income-statement.pdf",
    hasTextLayer: true,
    category: "finance",
  },
  {
    docId: "meridian-balance-sheet",
    label: "Meridian balance sheet",
    path: "/documents/meridian-balance-sheet.pdf",
    filename: "meridian-balance-sheet.pdf",
    hasTextLayer: true,
    category: "finance",
  },
  {
    docId: "northgate-auto-claim-fnol",
    label: "Northgate auto (FNOL)",
    path: "/documents/northgate-auto-claim-fnol.pdf",
    filename: "northgate-auto-claim-fnol.pdf",
    hasTextLayer: true,
    category: "claims",
  },
  // Added 2026-08-11. All ten documents above are printed business PDFs, so
  // the Describe feature's "Transcribe" preset had nothing to actually prove —
  // transcribing print is not a demonstration. These four are images (no PDF
  // wrapper, hence `hasTextLayer: false` like the other scans above) and range
  // from cursive to print on a form, which is what makes Transcribe interesting
  // again. Deliberately NOT thematically coherent like the other categories —
  // a recipe, a note and a form share nothing except being handwriting-adjacent
  // source material, which is the point of this category.
  //
  // The viewer opens these the same way it opens a PDF: NutrientViewer.load()
  // takes JPEG/JPG/PNG/TIFF natively in standalone mode, so DocViewer needed no
  // branch (https://www.nutrient.io/guides/web/viewer/images/).
  {
    docId: "apricot-cake-recipe",
    label: "Apricot cake recipe",
    path: "/documents/handwritten-cursive-apricot-cake-recipe.jpg",
    filename: "handwritten-cursive-apricot-cake-recipe.jpg",
    hasTextLayer: false,
    category: "handwriting",
  },
  {
    docId: "dear-magnus-thank-you-note",
    label: "Thank-you note",
    path: "/documents/handwritten-cursive-dear-magnus-thank-you-note.jpg",
    filename: "handwritten-cursive-dear-magnus-thank-you-note.jpg",
    hasTextLayer: false,
    category: "handwriting",
  },
  {
    docId: "heavenly-hamburgers-recipe",
    label: "Hamburger recipe card",
    path: "/documents/heavenly-hamburgers-recipe.jpeg",
    filename: "heavenly-hamburgers-recipe.jpeg",
    hasTextLayer: false,
    category: "handwriting",
  },
  {
    docId: "employment-application",
    label: "Employment application",
    path: "/documents/handwritten-employment-application.jpg",
    filename: "handwritten-employment-application.jpg",
    hasTextLayer: false,
    category: "handwriting",
  },
];

export function findDoc(docId: string): DocSummary | undefined {
  return DOCUMENTS.find((d) => d.docId === docId);
}
